### ISSUE TITLE
Very Minor: uncaught exception (invalid integer after out-of-range value)

### ISSUE THREAD

**Issue by crashdemons** [beautifulevilflower/LiberPrTools#1]
Example session:
```
Gematria Prime Vigenere Decipherer
Version 1 Release Version March 16, 2021.
This program was made by Angelo Fiore. email: beautifulevilflower@gmail.com
This is a calculator for Vigenere cipher values of the Gemtria Prime
Enter a rune's value from 0 to 28, then press "enter".

Your Input:82
Your entry is invalid.  Please enter a value between 0 and 28.
Your Input:x
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted
```

This is because while the initial input has errors caught for stroi (https://github.com/beautifulevilflower/LiberPrTools/blob/main/GPVigenere_Decipher_v1Release.cpp#L120) but
the secondary input after a range check does not have any try/catch: https://github.com/beautifulevilflower/LiberPrTools/blob/main/GPVigenere_Decipher_v1Release.cpp#L130

**Comment by beautifulevilflower** [comment]
Thank you for pointing out this bug, & for illustrating the problem clearly.
I uploaded a new build with the bug fixed.
